version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-server
    hostname: rmq
    ports:
      - "8080:15672"  # Management UI
      - "5672:5672"   # AMQP protocol port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

volumes:
  rabbitmq_data:
